# Generated by Django 5.0.14 on 2026-05-30 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('betting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='apuesta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apuestas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='apuestacombinada',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apuestas_combinadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='apuestacombinada',
            name='selecciones',
            field=models.ManyToManyField(related_name='combinadas', to='betting.cuota', verbose_name='Selecciones'),
        ),
        migrations.AddField(
            model_name='apuesta',
            name='cuota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apuestas', to='betting.cuota', verbose_name='Cuota seleccionada'),
        ),
        migrations.AddField(
            model_name='historialcuota',
            name='cuota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='betting.cuota'),
        ),
        migrations.AddField(
            model_name='mercado',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mercados', to='betting.evento', verbose_name='Evento'),
        ),
        migrations.AddField(
            model_name='cuota',
            name='mercado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='betting.mercado', verbose_name='Mercado'),
        ),
        migrations.AlterUniqueTogether(
            name='mercado',
            unique_together={('evento', 'tipo')},
        ),
        migrations.AlterUniqueTogether(
            name='cuota',
            unique_together={('mercado', 'seleccion')},
        ),
    ]
