# Generated by Django 5.0.14 on 2026-05-30 09:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadSospechosa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(choices=[('multiples_cuentas_ip', 'Múltiples cuentas desde misma IP'), ('patron_apuestas_identicas', 'Patrón de apuestas idénticas en grupo'), ('deposito_cashout_inmediato', 'Depósito seguido inmediatamente de cash-out'), ('lavado_bonos', 'Posible abuso de bonos'), ('apuestas_sin_riesgo', 'Apuestas sin riesgo (cubriendo todos los resultados)')], max_length=50, verbose_name='Tipo de alerta')),
                ('descripcion', models.TextField(verbose_name='Descripción detallada')),
                ('revisado', models.BooleanField(default=False, verbose_name='Revisado por admin')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('revisado_en', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Actividad sospechosa',
                'verbose_name_plural': 'Actividades sospechosas',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_evento', models.CharField(choices=[('apuesta', 'Apuesta'), ('wallet', 'Movimiento de wallet'), ('odds', 'Cambio de cuota'), ('usuario', 'Cambio de usuario/KYC'), ('login', 'Autenticación'), ('admin', 'Acción de administrador'), ('antifraude', 'Detección de fraude')], max_length=20, verbose_name='Tipo de evento')),
                ('payload', models.JSONField(verbose_name='Datos del evento')),
                ('hash_anterior', models.CharField(max_length=64, verbose_name='Hash del registro anterior')),
                ('hash_actual', models.CharField(max_length=64, verbose_name='Hash de este registro')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Registro de auditoría',
                'verbose_name_plural': 'Registros de auditoría',
                'ordering': ['creado_en'],
            },
        ),
    ]
